package questions;

public enum Sponsor {
    CISCO, NEXTJUMP, VISA, ATLASCITY, SCHLUMBERGER, THOUGHTMACHINE, AMEX,
    GRESEARCH, FUNDAPPS, BLACKROCK, IMPROBABLE, NETCRAFT, PALANTIR, TWOSIGMA,
    QUANTERIUM, AIMBRAIN, POLYAI
}
